-- Generated by tools/wireshark/gen_lua_pdu_table.py -- do not hand-edit.
-- Source: pdu_db_example.json (2 CAN/CAN-FD messages, 0 skipped)
return {
  [123] = { name = "Motor_1", length = 8,
    signals = {
      { name = "Clamp15", start = 12, length = 2, byte_order = "intel", factor = 1.0, offset = 0.0, unit = "", enum = {[0] = "Off", [1] = "On", [2] = "Error", [3] = "NotAvailable"} },
      { name = "MotorSpeed", start = 0, length = 16, byte_order = "intel", factor = 0.5, offset = 0.0, unit = "rpm" }
    } },
  [456] = { name = "Motor_1_GW", length = 16,
    signals = {
      { name = "Clamp15", start = 12, length = 2, byte_order = "intel", factor = 1.0, offset = 0.0, unit = "", enum = {[0] = "Off", [1] = "On", [2] = "Error", [3] = "NotAvailable"} },
      { name = "MotorSpeed", start = 0, length = 16, byte_order = "intel", factor = 0.5, offset = 0.0, unit = "rpm" }
    } },
}
