"""
BoAt Platform — PDU Database to Lua Lookup Table Generator

Converts a BoAt pdu_db.json (see boat-platform/config/pdu_db.schema.json)
into a static Lua table keyed by CAN arbitration ID, for use by
boat_pdu_dissector.lua. Only CAN/CAN-FD messages are included -- Ethernet
PDU entries (BusType ETH_PDU) key off a PduId, not a wire CAN ID, and have
no CAN-frame representation to attach signal decoding to.

Regenerate this whenever pdu_db.json changes (same idea as
sdk/python/boat/stubs/generate_stubs.sh for proto stubs -- the output is a
committed, regenerate-on-demand artifact, not something hand-edited).

Deliberately self-contained (stdlib only, no `boat` package import): the
Wireshark plugin folder this lives alongside is often copied out of the
repo entirely for install, and pdu_db.json's shape is simple enough that
pulling in boat.pdu_db.PduDatabase for this one read-only pass isn't worth
the cross-directory import dependency.

Usage:
    python3 tools/wireshark/gen_lua_pdu_table.py --db pdu_db.json -o tools/wireshark/boat_pdu_db.lua
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

_WIRE_BUS_TYPES = ("CAN", "CANFD")


def _lua_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _signal_to_lua(sig: dict[str, Any]) -> str:
    byte_order = "motorola" if sig.get("ByteOrder") == 1 else "intel"
    factor = sig.get("Factor", 1.0) or 1.0
    offset = sig.get("Offset", 0.0) or 0.0
    parts = [
        f'name = {_lua_string(sig["SignalName"])}',
        f'start = {sig["StartPos"]}',
        f'length = {sig["Length"]}',
        f'byte_order = "{byte_order}"',
        f"factor = {factor!r}",
        f"offset = {offset!r}",
        f'unit = {_lua_string(sig.get("Unit") or "")}',
    ]
    mux_value = sig.get("MuxValue")
    if mux_value is not None:
        parts.append(f"mux_value = {mux_value}")
    if sig.get("IsMuxor"):
        parts.append("is_muxor = true")
    enum_values = sig.get("EnumValues")
    if enum_values:
        entries = ", ".join(f"[{k}] = {_lua_string(v)}" for k, v in enum_values.items())
        parts.append(f"enum = {{{entries}}}")
    return "{ " + ", ".join(parts) + " }"


def _message_to_lua(msg: dict[str, Any]) -> str:
    signals = ",\n      ".join(_signal_to_lua(s) for s in msg.get("signals", []))
    return (
        f'{{ name = {_lua_string(msg["MessageName"])}, length = {msg.get("Length", 0)},\n'
        f"    signals = {{\n      {signals}\n    }} }}"
    )


def generate(db_path: Path) -> str:
    with open(db_path) as f:
        raw = json.load(f)

    by_can_id: dict[int, dict[str, Any]] = {}
    skipped = 0
    for msg in raw.get("messages", []):
        if msg.get("BusType") not in _WIRE_BUS_TYPES:
            continue
        can_id = msg.get("Identifier")
        if can_id is None:
            skipped += 1
            continue
        by_can_id[can_id] = msg

    lines = [
        "-- Generated by tools/wireshark/gen_lua_pdu_table.py -- do not hand-edit.",
        f"-- Source: {db_path.name} ({len(by_can_id)} CAN/CAN-FD messages, {skipped} skipped)",
        "return {",
    ]
    for can_id, msg in sorted(by_can_id.items()):
        lines.append(f"  [{can_id}] = {_message_to_lua(msg)},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--db", required=True, type=Path, help="Path to pdu_db.json")
    parser.add_argument("-o", "--output", required=True, type=Path, help="Output .lua file path")
    args = parser.parse_args()

    if not args.db.exists():
        print(f"error: {args.db} not found", file=sys.stderr)
        return 1

    lua_source = generate(args.db)
    # newline="\n" keeps output LF-only on every platform -- the default
    # text-mode write translates \n -> \r\n on Windows, which is harmless
    # to Lua's parser but inconsistent with the rest of this repo.
    with open(args.output, "w", encoding="utf-8", newline="\n") as f:
        f.write(lua_source)
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
