# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from boat.v1 import can_tp_pb2 as boat_dot_v1_dot_can__tp__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in boat/v1/can_tp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CanTpServiceStub:
    """Exposes the CanTp plugin's live gateway-side instance(s) (loaded via
    BOAT_NODE_PLUGINS, one per CAN interface) to CLI/SDK clients.
    See PluginManager::FindService("can_tp:" + iface).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Configure = channel.unary_unary(
                '/boat.v1.CanTpService/Configure',
                request_serializer=boat_dot_v1_dot_can__tp__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_can__tp__pb2.ConfigureResponse.FromString,
                _registered_method=True)
        self.Send = channel.unary_unary(
                '/boat.v1.CanTpService/Send',
                request_serializer=boat_dot_v1_dot_can__tp__pb2.SendRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_can__tp__pb2.SendResponse.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/boat.v1.CanTpService/ListSessions',
                request_serializer=boat_dot_v1_dot_can__tp__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_can__tp__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.RemoveSession = channel.unary_unary(
                '/boat.v1.CanTpService/RemoveSession',
                request_serializer=boat_dot_v1_dot_can__tp__pb2.RemoveSessionRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_can__tp__pb2.RemoveSessionResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/boat.v1.CanTpService/Subscribe',
                request_serializer=boat_dot_v1_dot_can__tp__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_can__tp__pb2.CanTpRxEvent.FromString,
                _registered_method=True)
        self.SubscribeErrors = channel.unary_stream(
                '/boat.v1.CanTpService/SubscribeErrors',
                request_serializer=boat_dot_v1_dot_can__tp__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_can__tp__pb2.CanTpErrorEvent.FromString,
                _registered_method=True)


class CanTpServiceServicer:
    """Exposes the CanTp plugin's live gateway-side instance(s) (loaded via
    BOAT_NODE_PLUGINS, one per CAN interface) to CLI/SDK clients.
    See PluginManager::FindService("can_tp:" + iface).
    """

    def Configure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeErrors(self, request, context):
        """Same nsdu_ids/iface scoping convention as Subscribe (SubscribeRequest
        is shared between the two).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CanTpServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=boat_dot_v1_dot_can__tp__pb2.ConfigureRequest.FromString,
                    response_serializer=boat_dot_v1_dot_can__tp__pb2.ConfigureResponse.SerializeToString,
            ),
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=boat_dot_v1_dot_can__tp__pb2.SendRequest.FromString,
                    response_serializer=boat_dot_v1_dot_can__tp__pb2.SendResponse.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=boat_dot_v1_dot_can__tp__pb2.ListSessionsRequest.FromString,
                    response_serializer=boat_dot_v1_dot_can__tp__pb2.ListSessionsResponse.SerializeToString,
            ),
            'RemoveSession': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveSession,
                    request_deserializer=boat_dot_v1_dot_can__tp__pb2.RemoveSessionRequest.FromString,
                    response_serializer=boat_dot_v1_dot_can__tp__pb2.RemoveSessionResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=boat_dot_v1_dot_can__tp__pb2.SubscribeRequest.FromString,
                    response_serializer=boat_dot_v1_dot_can__tp__pb2.CanTpRxEvent.SerializeToString,
            ),
            'SubscribeErrors': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeErrors,
                    request_deserializer=boat_dot_v1_dot_can__tp__pb2.SubscribeRequest.FromString,
                    response_serializer=boat_dot_v1_dot_can__tp__pb2.CanTpErrorEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boat.v1.CanTpService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('boat.v1.CanTpService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CanTpService:
    """Exposes the CanTp plugin's live gateway-side instance(s) (loaded via
    BOAT_NODE_PLUGINS, one per CAN interface) to CLI/SDK clients.
    See PluginManager::FindService("can_tp:" + iface).
    """

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.CanTpService/Configure',
            boat_dot_v1_dot_can__tp__pb2.ConfigureRequest.SerializeToString,
            boat_dot_v1_dot_can__tp__pb2.ConfigureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.CanTpService/Send',
            boat_dot_v1_dot_can__tp__pb2.SendRequest.SerializeToString,
            boat_dot_v1_dot_can__tp__pb2.SendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.CanTpService/ListSessions',
            boat_dot_v1_dot_can__tp__pb2.ListSessionsRequest.SerializeToString,
            boat_dot_v1_dot_can__tp__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.CanTpService/RemoveSession',
            boat_dot_v1_dot_can__tp__pb2.RemoveSessionRequest.SerializeToString,
            boat_dot_v1_dot_can__tp__pb2.RemoveSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/boat.v1.CanTpService/Subscribe',
            boat_dot_v1_dot_can__tp__pb2.SubscribeRequest.SerializeToString,
            boat_dot_v1_dot_can__tp__pb2.CanTpRxEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeErrors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/boat.v1.CanTpService/SubscribeErrors',
            boat_dot_v1_dot_can__tp__pb2.SubscribeRequest.SerializeToString,
            boat_dot_v1_dot_can__tp__pb2.CanTpErrorEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
