# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: boat/v1/node_plugin.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'boat/v1/node_plugin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from boat.v1 import common_pb2 as boat_dot_v1_dot_common__pb2
from boat.v1 import plugin_pb2 as boat_dot_v1_dot_plugin__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x62oat/v1/node_plugin.proto\x12\x07\x62oat.v1\x1a\x14\x62oat/v1/common.proto\x1a\x14\x62oat/v1/plugin.proto\"B\n\x16ListNodePluginsRequest\x12(\n\x04page\x18\x01 \x01(\x0b\x32\x1a.boat.v1.PaginationRequest\"f\n\x17ListNodePluginsResponse\x12 \n\x07plugins\x18\x01 \x03(\x0b\x32\x0f.boat.v1.Plugin\x12)\n\x04page\x18\x02 \x01(\x0b\x32\x1b.boat.v1.PaginationResponse\"-\n\x18GetNodePluginInfoRequest\x12\x11\n\tplugin_id\x18\x01 \x01(\t\"=\n\x17UnloadNodePluginRequest\x12\x11\n\tplugin_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63onfirm\x18\x02 \x01(\x08\"Q\n\x18UnloadNodePluginResponse\x12\x10\n\x08unloaded\x18\x01 \x01(\x08\x12#\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x14.boat.v1.ErrorDetail2\x93\x02\n\x11NodePluginService\x12T\n\x0fListNodePlugins\x12\x1f.boat.v1.ListNodePluginsRequest\x1a .boat.v1.ListNodePluginsResponse\x12O\n\x11GetNodePluginInfo\x12!.boat.v1.GetNodePluginInfoRequest\x1a\x17.boat.v1.PluginResponse\x12W\n\x10UnloadNodePlugin\x12 .boat.v1.UnloadNodePluginRequest\x1a!.boat.v1.UnloadNodePluginResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'boat.v1.node_plugin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTNODEPLUGINSREQUEST']._serialized_start=82
  _globals['_LISTNODEPLUGINSREQUEST']._serialized_end=148
  _globals['_LISTNODEPLUGINSRESPONSE']._serialized_start=150
  _globals['_LISTNODEPLUGINSRESPONSE']._serialized_end=252
  _globals['_GETNODEPLUGININFOREQUEST']._serialized_start=254
  _globals['_GETNODEPLUGININFOREQUEST']._serialized_end=299
  _globals['_UNLOADNODEPLUGINREQUEST']._serialized_start=301
  _globals['_UNLOADNODEPLUGINREQUEST']._serialized_end=362
  _globals['_UNLOADNODEPLUGINRESPONSE']._serialized_start=364
  _globals['_UNLOADNODEPLUGINRESPONSE']._serialized_end=445
  _globals['_NODEPLUGINSERVICE']._serialized_start=448
  _globals['_NODEPLUGINSERVICE']._serialized_end=723
# @@protoc_insertion_point(module_scope)
