# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from boat.v1 import node_plugin_pb2 as boat_dot_v1_dot_node__plugin__pb2
from boat.v1 import plugin_pb2 as boat_dot_v1_dot_plugin__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in boat/v1/node_plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodePluginServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListNodePlugins = channel.unary_unary(
                '/boat.v1.NodePluginService/ListNodePlugins',
                request_serializer=boat_dot_v1_dot_node__plugin__pb2.ListNodePluginsRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_node__plugin__pb2.ListNodePluginsResponse.FromString,
                _registered_method=True)
        self.GetNodePluginInfo = channel.unary_unary(
                '/boat.v1.NodePluginService/GetNodePluginInfo',
                request_serializer=boat_dot_v1_dot_node__plugin__pb2.GetNodePluginInfoRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_plugin__pb2.PluginResponse.FromString,
                _registered_method=True)
        self.UnloadNodePlugin = channel.unary_unary(
                '/boat.v1.NodePluginService/UnloadNodePlugin',
                request_serializer=boat_dot_v1_dot_node__plugin__pb2.UnloadNodePluginRequest.SerializeToString,
                response_deserializer=boat_dot_v1_dot_node__plugin__pb2.UnloadNodePluginResponse.FromString,
                _registered_method=True)


class NodePluginServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListNodePlugins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodePluginInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadNodePlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodePluginServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListNodePlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodePlugins,
                    request_deserializer=boat_dot_v1_dot_node__plugin__pb2.ListNodePluginsRequest.FromString,
                    response_serializer=boat_dot_v1_dot_node__plugin__pb2.ListNodePluginsResponse.SerializeToString,
            ),
            'GetNodePluginInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodePluginInfo,
                    request_deserializer=boat_dot_v1_dot_node__plugin__pb2.GetNodePluginInfoRequest.FromString,
                    response_serializer=boat_dot_v1_dot_plugin__pb2.PluginResponse.SerializeToString,
            ),
            'UnloadNodePlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadNodePlugin,
                    request_deserializer=boat_dot_v1_dot_node__plugin__pb2.UnloadNodePluginRequest.FromString,
                    response_serializer=boat_dot_v1_dot_node__plugin__pb2.UnloadNodePluginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boat.v1.NodePluginService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('boat.v1.NodePluginService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodePluginService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListNodePlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.NodePluginService/ListNodePlugins',
            boat_dot_v1_dot_node__plugin__pb2.ListNodePluginsRequest.SerializeToString,
            boat_dot_v1_dot_node__plugin__pb2.ListNodePluginsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodePluginInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.NodePluginService/GetNodePluginInfo',
            boat_dot_v1_dot_node__plugin__pb2.GetNodePluginInfoRequest.SerializeToString,
            boat_dot_v1_dot_plugin__pb2.PluginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadNodePlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boat.v1.NodePluginService/UnloadNodePlugin',
            boat_dot_v1_dot_node__plugin__pb2.UnloadNodePluginRequest.SerializeToString,
            boat_dot_v1_dot_node__plugin__pb2.UnloadNodePluginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
