# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: boat/v1/pdu.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'boat/v1/pdu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x62oat/v1/pdu.proto\x12\x07\x62oat.v1\"\x87\x01\n\x08PduRoute\x12\x0e\n\x06pdu_id\x18\x01 \x01(\r\x12(\n\ttransport\x18\x02 \x01(\x0e\x32\x15.boat.v1.PduTransport\x12\r\n\x05iface\x18\x03 \x01(\t\x12\x0f\n\x07vlan_id\x18\x04 \x01(\r\x12\x0e\n\x06\x63\x61n_id\x18\x05 \x01(\r\x12\x11\n\tethertype\x18\x06 \x01(\r\"w\n\x08PduFrame\x12\x0e\n\x06pdu_id\x18\x01 \x01(\r\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x14\n\x0ctimestamp_ns\x18\x03 \x01(\x04\x12%\n\x06source\x18\x04 \x01(\x0e\x32\x15.boat.v1.PduTransport\x12\r\n\x05iface\x18\x05 \x01(\t\"0\n\x0eSendPduRequest\x12\x1e\n\x03pdu\x18\x01 \x01(\x0b\x32\x11.boat.v1.PduFrame\"#\n\x0fSendPduResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\"\'\n\x14SubscribePdusRequest\x12\x0f\n\x07pdu_ids\x18\x01 \x03(\r\"9\n\x15\x43onfigureRouteRequest\x12 \n\x05route\x18\x01 \x01(\x0b\x32\x11.boat.v1.PduRoute\"$\n\x16\x43onfigureRouteResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x13\n\x11ListRoutesRequest\"7\n\x12ListRoutesResponse\x12!\n\x06routes\x18\x01 \x03(\x0b\x32\x11.boat.v1.PduRoute*`\n\x0cPduTransport\x12\x1d\n\x19PDU_TRANSPORT_UNSPECIFIED\x10\x00\x12\x15\n\x11PDU_TRANSPORT_CAN\x10\x01\x12\x1a\n\x16PDU_TRANSPORT_ETHERNET\x10\x02\x32\xa9\x02\n\nPduService\x12<\n\x07SendPdu\x12\x17.boat.v1.SendPduRequest\x1a\x18.boat.v1.SendPduResponse\x12\x43\n\rSubscribePdus\x12\x1d.boat.v1.SubscribePdusRequest\x1a\x11.boat.v1.PduFrame0\x01\x12Q\n\x0e\x43onfigureRoute\x12\x1e.boat.v1.ConfigureRouteRequest\x1a\x1f.boat.v1.ConfigureRouteResponse\x12\x45\n\nListRoutes\x12\x1a.boat.v1.ListRoutesRequest\x1a\x1b.boat.v1.ListRoutesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'boat.v1.pdu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PDUTRANSPORT']._serialized_start=592
  _globals['_PDUTRANSPORT']._serialized_end=688
  _globals['_PDUROUTE']._serialized_start=31
  _globals['_PDUROUTE']._serialized_end=166
  _globals['_PDUFRAME']._serialized_start=168
  _globals['_PDUFRAME']._serialized_end=287
  _globals['_SENDPDUREQUEST']._serialized_start=289
  _globals['_SENDPDUREQUEST']._serialized_end=337
  _globals['_SENDPDURESPONSE']._serialized_start=339
  _globals['_SENDPDURESPONSE']._serialized_end=374
  _globals['_SUBSCRIBEPDUSREQUEST']._serialized_start=376
  _globals['_SUBSCRIBEPDUSREQUEST']._serialized_end=415
  _globals['_CONFIGUREROUTEREQUEST']._serialized_start=417
  _globals['_CONFIGUREROUTEREQUEST']._serialized_end=474
  _globals['_CONFIGUREROUTERESPONSE']._serialized_start=476
  _globals['_CONFIGUREROUTERESPONSE']._serialized_end=512
  _globals['_LISTROUTESREQUEST']._serialized_start=514
  _globals['_LISTROUTESREQUEST']._serialized_end=533
  _globals['_LISTROUTESRESPONSE']._serialized_start=535
  _globals['_LISTROUTESRESPONSE']._serialized_end=590
  _globals['_PDUSERVICE']._serialized_start=691
  _globals['_PDUSERVICE']._serialized_end=988
# @@protoc_insertion_point(module_scope)
